#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/
management:
  endpoints:
    web:
      exposure:
        include: '*'
#server:
#  port: 9090
spring:
  application:
    name: WELCOME-API

  boot:
    admin:
      client:
        url: http://localhost:1111/
